M48
; DRILL file {KiCad (6.0.1)} date Sun Jan 23 20:41:19 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-23T20:41:19-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C2.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C5.200
%
G90
G05
T1
X71.132Y-83.616
X71.679Y-73.18
T2
X106.0Y-78.4
X119.2Y-78.4
T3
X57.6Y-87.9
X71.261Y-81.144
X71.549Y-75.652
X167.6Y-87.9
T4
X60.617Y-67.617
X82.183Y-89.183
T5
X159.6Y-68.4
T6
X75.6Y-98.4
T4
X172.1Y-103.4G85X172.7Y-103.4
G05
T0
M30
