M48
; DRILL file {KiCad (6.0.1)} date Mon Mar 21 17:48:07 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-21T17:48:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C5.200
%
G90
G05
T1
X150.0Y-94.775
X150.0Y-105.225
T2
X149.2Y-85.525
T3
X150.0Y-97.25
X150.0Y-102.75
T4
X164.85Y-90.0
T0
M30
